FROM node:18-alpine as builder

WORKDIR /build

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:18-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=builder /build/dist dist

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "5173"]
