export type UserRole = "citizen" | "admin" | "worker";

export interface User {
  id: string;
  name: string;
  email: string;
  phone: string;
  role: UserRole;
  token: string;
}

export type ComplaintStatus = "pending" | "assigned" | "in_progress" | "resolved" | "rejected";

export type ComplaintCategory =
  | "road"
  | "garbage"
  | "water"
  | "drainage"
  | "streetlight"
  | "illegal-dumping";

export interface Complaint {
  id: string;
  complaintId: string; // e.g. CMP-123456, generated by backend
  title: string;
  description: string;
  category: ComplaintCategory;
  status: ComplaintStatus;
  image?: string;
  photoUrl?: string; // Backend might use this
  address?: string; // Backend flat field
  latitude?: number; // Backend flat field
  longitude?: number; // Backend flat field
  location: {
    lat: number;
    lng: number;
    address: string;
  };
  citizenId: string;
  citizenName?: string;
  assignedWorkerId?: string;
  assignedWorkerName?: string;
  createdAt: string;
  updatedAt: string;
  timeline: TimelineEntry[];
}

export interface TimelineEntry {
  id: string;
  status: ComplaintStatus;
  message: string;
  date: string;
  by: string;
}

export interface Worker {
  id: string;
  name: string;
  email: string;
}
